spring:
  datasource:
    url: jdbc:postgresql://192.168.137.30:5432/postgres
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 0
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 2000000
      connection-timeout: 30000
      pool-name: ApiGatewayHikariCP
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: sv-kfk-dev-01.sberinsur.local:9093,sv-kfk-dev-02.sberinsur.local:9093,sv-kfk-dev-03.sberinsur.local:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        sasl.mechanism: "PLAIN"
        security.protocol: "SASL_PLAINTEXT"
        ssl.endpoint.identification.algorithm: "NONE"
        sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username='fuse' password='UCWjTLZgjeEe';"
    topic:
      logs: redirect-logs  # Топик для логирования

server:
  port: 8081
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,application/json
    min-response-size: 1024

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
#  security:
#    enabled: true

